fix: select 0 as x union select 1 from dual
Signed-off-by: Andrei Sura <andrei.sura@sharpspring.com>

https://github.com/vitessio/vitess/runs/1500548128

W1204 18:37:57.493639   21874 tabletserver.go:1337] Code: ABORTED
transaction 1607107077491657808: ended at 2020-12-04 18:37:57.493 UTC (closed) (CallerID: d)
: Sql: "commit", BindVars: {}
E1204 18:37:57.508877   21874 message_manager.go:384] Terminating connection due to error sending field info: EOF
--- FAIL: TestQueryExecutorTableAclDualTableExempt (0.00s)
panic: unknown error: query: '(select 0 as x from dual where 1 != 1) union (select 1 as y from dual where 1 != 1)' is not supported on fakesqldb (errno 1105) (sqlstate HY000) during query: (select 0 as x from dual where 1 != 1) union (select 1 as y from dual where 1 != 1) [recovered]
	panic: unknown error: query: '(select 0 as x from dual where 1 != 1) union (select 1 as y from dual where 1 != 1)' is not supported on fakesqldb (errno 1105) (sqlstate HY000) during query: (select 0 as x from dual where 1 != 1) union (select 1 as y from dual where 1 != 1)