Upgrade pgzip to v1.2.4
This upgrades pgzip to include a
[fix](https://github.com/klauspost/pgzip/pull/33) to prevent negative
byte counts being returned from `pgzip.Write`, which cause panics in
`bufio`.

These panics manifest when using compressed xtrabackup backups as:

```
Error: <_Rendezvous of RPC that terminated with
(StatusCode.UNKNOWN, caught panic during Backup: bufio: writer returned negative count from Write)>
```

Signed-off-by: Andrew Mason <amason@slack-corp.com>