RFC: Should ApplySchema skip shards which have no database/are currently not serving?
This test simulates the situation where a new shard was created (e.g. as
part of a resharding) but it's not actively used.

ApplySchema iterates over all shards and fails to process this once
because its database is empty.

Do we want the code to be more robust in this corner case?
e.g. skip tablets which don't have a database initialized.
Or should we better mark this in the topology when a shard is currently in production or not?

For reference, here is the full error of the failed ApplySchema:

$ ./schema.py
Successfully read all schema changes.
Successfully validate all sqls.
Executor finished, result: {
  "FailedShards": [
    {
      "Shard": "2",
      "Err": "remote error for test_nj-0000062351: TabletManager.ExecuteFetchAsDba on test_nj-0000062351 error: No database selected (errno 1046) during query: CREATE TABLE vt_select_test01 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB"
    }
  ],
  "SuccessShards": [
    {
      "Shard": "0",
      "Result": {
        "Fields": [],
        "RowsAffected": 0,
        "InsertId": 0,
        "Rows": [],
        "Err": {
          "Code": 0,
          "Message": ""
        }
      }
    },
    {
      "Shard": "1",
      "Result": {
        "Fields": [],
        "RowsAffected": 0,
        "InsertId": 0,
        "Rows": [],
        "Err": {
          "Code": 0,
          "Message": ""
        }
      }
    }
  ],
  "CurSqlIndex": 0,
  "Sqls": [
    "CREATE TABLE vt_select_test01 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test02 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test03 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test04 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB"
  ],
  "ExecutorErr": "",
  "TotalTimeSpent": 111250633
}
-- 2015-06-05 18:40:38,590 utils:49 INFO ===== E
-- 2015-06-05 18:40:42,693 utils:49 INFO ===== ======================================================================
-- 2015-06-05 18:40:42,693 utils:49 INFO ===== ERROR: test_schema_changes (__main__.TestSchema)
-- 2015-06-05 18:40:42,693 utils:49 INFO ===== ----------------------------------------------------------------------
-- 2015-06-05 18:40:42,694 utils:49 INFO ===== Traceback (most recent call last):
  File "./schema.py", line 198, in test_schema_changes
    self._apply_schema(test_keyspace, schema_changes)
  File "./schema.py", line 158, in _apply_schema
    raise_on_error=True)
  File "/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/test/utils.py", line 599, in run_vtctl
    result = vtctld_connection.execute_vtctl_command(clargs, info_to_debug=True, action_timeout=120)
  File "/home/mberlin/workspace/vitess/py-vtdb/vtctl/gorpc_vtctl_client.py", line 62, in execute_vtctl_command
    e = self.client.stream_next()
  File "/home/mberlin/workspace/vitess/py-vtdb/net/gorpc.py", line 365, in stream_next
    raise AppError(response.error)
AppError: Schema change failed, ExecuteResult: {
  "FailedShards": [
    {
      "Shard": "2",
      "Err": "remote error for test_nj-0000062351: TabletManager.ExecuteFetchAsDba on test_nj-0000062351 error: No database selected (errno 1046) during query: CREATE TABLE vt_select_test01 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB"
    }
  ],
  "SuccessShards": [
    {
      "Shard": "0",
      "Result": {
        "Fields": [],
        "RowsAffected": 0,
        "InsertId": 0,
        "Rows": [],
        "Err": {
          "Code": 0,
          "Message": ""
        }
      }
    },
    {
      "Shard": "1",
      "Result": {
        "Fields": [],
        "RowsAffected": 0,
        "InsertId": 0,
        "Rows": [],
        "Err": {
          "Code": 0,
          "Message": ""
        }
      }
    }
  ],
  "CurSqlIndex": 0,
  "Sqls": [
    "CREATE TABLE vt_select_test01 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test02 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test03 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB",
    "CREATE TABLE vt_select_test04 (             `id` BIGINT(20) not NULL,             `msg` varchar(64),             PRIMARY KEY (`id`)             ) ENGINE=InnoDB"
  ],
  "ExecutorErr": "",
  "TotalTimeSpent": 111250633
}

-- 2015-06-05 18:40:42,694 utils:49 INFO ===== ----------------------------------------------------------------------
-- 2015-06-05 18:40:42,694 utils:49 INFO ===== Ran 1 test in 9.559s
-- 2015-06-05 18:40:42,694 utils:49 INFO ===== FAILED
-- 2015-06-05 18:40:42,694 utils:49 INFO ===== FAILED (errors=1)