Fix for exception in test harness due to attribute out of scope/missing.
    Traceback (most recent call last):
      File "./occ_test.py", line 233, in <module>
        env.tearDown()
      File "./occ_test.py", line 126, in tearDown
        self.vtstderr.close()
    AttributeError: 'TestEnv' object has no attribute 'vtstderr'