Switch gotestsum output format
Switches gotestsum output format to `pkgname-and-test-fails`, which
outputs a line per package, or the full logs for a test if it fails:

```
pkgname-and-test-fails:
✓ pkg/utils (0.01s)
FAIL pkg/api [build failed]
  --- FAIL: TestUserAuthentication (0.00s)
      api_test.go:45: expected status 200, got 401
```

The current format for each test makes it really noisy and often breaks
the GitHub UI (and you then need to parse the raw logs).

Signed-off-by: Mohamed Hamza <mhamza@fastmail.com>